import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :blogs_portfolio, BlogsPortfolioWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: BlogsPortfolio.Finch

config :blogs_portfolio, :uploader, adapter: Clients.Storage.S3

config :blogs_portfolio,
  s3_region: "us-east-1",
  s3_access_key_id: System.get_env("S3_ACCESS_KEY_ID"),
  s3_secret_key_access: System.get_env("S3_SECRET_KEY_ACCESS"),
  s3_bucket_name: System.get_env("S3_BUCKET_NAME")

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
